owner: derailed-org
repo: status

sites:
  - name: Derailed Site
    url: https://derailed.top
    expectedStatusCodes:
      - 200
      - 403
  - name: Derailed API
    url: https://api.derailed.top
    expectedStatusCodes:
      - 404
      - 403

status-website:
  # TODO: Change Logo URL
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/derailedapp/derailed/refs/heads/master/app/static/derailed-text.svg
  cname: status.derailed.top
  theme: night
  introTitle: "**Derailed Status**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Derailed Status"
  commitAuthorEmail: "status@derailed.top"
